import { ProductPK } from "./product";

export interface IStoreProductOutput {
    storeProductId: StoreProductPK;
    baseStoreProductId: StoreProductPK;
    upc: ProductPK;
    price: number;
    quantity: number;
    // joined for proper display
    productName: string;
    manufacturer: string;
}

export interface IStoreProductInput {
    baseStoreProductId: StoreProductPK | null; // own id is autogenerated, but base's id is needed
    upc: ProductPK;
    price: number;
    quantity: number;
}

export type StoreProductPK = number;
